language: ruby
rvm:
  - 2.2.2
jdk:
  - oraclejdk8

sudo: false
cache: bundler

env:
  global:
    - export LC_CTYPE=ja_JP.UTF-8
    - GIT_COMMITTER_NAME=kubosho_
    - GIT_COMMITTER_EMAIL=ta2@o2p.jp
    - GIT_AUTHOR_NAME=kubosho_
    - GIT_AUTHOR_EMAIL=ta2@o2p.jp
    - secure: II4z0KgjvpyK0sAyI0bE+NvSuVfDdcHyZlVlgQyzkmaOuGLogjbeGCu/mQUW6tcMeMWhFAA1S91o+DSHlwIcEw0Dur755WyXzzWoo1QAsrjvz/7mLIzvrs2Ahse5FzBkIoeVtjXIC7jIHLTdsR9Y7Pqp64OLc6BKKnqxCAFptVZjppJ8oAWyqt+FViXyliPUg2W3wBKai7bCaZU1You3eldGGpZ+6eNhurt3p/7ydNjccSgYHnD/rlcdLCOmVshzMOCeS3n3dz/jaVYqouHr8Px+FL/HgQ2IbyGGEx00JaePQIF4koQwqKNj0T4C8cdh3ltRNnE+4Qqya+hkZGKfRng7lz5FFHBZXHvPISyQ4vGWMbciE6J/bTEYCcZogsQ4tncKih48fuwDD/elmDTh4xBHfL7pVR/Oez7fCNJzDfA9vyEaaHLI4IhwTm29cAlIwPVpHJP+ExNb92ry7oUxHRX2wx9ho2hYxXIriKvriDE/HzvQMUWJNS6v+yTIjd5KS1MPYWBgjgkpYksyujZbg7A1H1exHI4HNhOsWyrYHcM9aGZBWXdo0w1OEvaL8Quai1H7maAuk/gtb7CvxgM5CsOYYu4On5GWg8pG+KWxqDH66mD/QQCbKIgbDIdQOx7sRsGMoI+SkhZiS8moUS9DwUA7y7UpM/kAPWROlPjyQ+I=

before_script:
  - '[ "$GH_TOKEN" ] && bundle exec rake ci:setup > /dev/null'

script:
  - bundle exec rake redpen
  - bundle exec rake html
  - bundle exec rake epub

after_success:
  - '[ "$TRAVIS_BRANCH" == "master" ] && [ "${TRAVIS_PULL_REQUEST}" = "false" ] && [ "$GH_TOKEN" ] && bundle exec rake ci:publish > /dev/null'
